version: '3.8'

services:
  streamsnap:
    image: ghcr.io/brentley/streamsnap:latest
    container_name: streamsnap
    restart: unless-stopped
    environment:
      - GIT_COMMIT=${GIT_COMMIT:-unknown}
      - BUILD_DATE=${BUILD_DATE:-unknown}
      - VERSION=${VERSION:-1.0.0}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - streamsnap_network
    labels:
      - "com.centurylinklabs.watchtower.scope=streamsnap"
      - "autoheal.streamsnap=true"
    volumes:
      - streamsnap_config:/app/config
      - streamsnap_logs:/app/logs

  watchtower:
    image: containrrr/watchtower
    container_name: streamsnap-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_SCOPE=streamsnap
      - WATCHTOWER_POLL_INTERVAL=30
    command: --interval 30 --scope streamsnap
    networks:
      - streamsnap_network
    labels:
      - "com.centurylinklabs.watchtower.scope=streamsnap"
      - "autoheal.streamsnap=true"

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: streamsnap-autoheal
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Use project-specific label instead of generic 'autoheal'
      - AUTOHEAL_CONTAINER_LABEL=autoheal.streamsnap
      - AUTOHEAL_INTERVAL=5
      - AUTOHEAL_START_PERIOD=30
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
      - AUTOHEAL_ONLY_MONITOR_RUNNING=true
      # Only monitor containers in this network
      - AUTOHEAL_CONTAINER_LABEL_ALL=false
    networks:
      - streamsnap_network
    labels:
      - "com.centurylinklabs.watchtower.scope=streamsnap"
      # Don't heal the healer itself
      - "autoheal.streamsnap=false"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: streamsnap-cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - streamsnap_network
    labels:
      - "com.centurylinklabs.watchtower.scope=streamsnap"
      - "autoheal.streamsnap=true"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://streamsnap:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  streamsnap_network:
    driver: bridge
    name: streamsnap_network

volumes:
  streamsnap_config:
    name: streamsnap_config
  streamsnap_logs:
    name: streamsnap_logs