
services:
  streamsnap:
    build: .
    container_name: streamsnap
    restart: unless-stopped
    environment:
      - GIT_COMMIT=${GIT_COMMIT:-unknown}
      - BUILD_DATE=${BUILD_DATE:-unknown}
      - VERSION=${VERSION:-1.0.0}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_MODEL=gpt-4o
      - AZURE_OPENAI_API_VERSION=2025-01-01-preview
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - streamsnap_network
    labels:
      - "com.centurylinklabs.watchtower.scope=streamsnap"
      - "autoheal.streamsnap=true"
    volumes:
      - streamsnap_config:/app/config
      - streamsnap_logs:/app/logs

  watchtower:
    image: containrrr/watchtower
    container_name: streamsnap-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_SCOPE=streamsnap
      - REPO_USER=${REPO_USER}
      - REPO_PASS=${REPO_PASS}
    # Polls for new images every 30 seconds - lifecycle hooks are label-based, not command flags
    command: --interval 30 --scope streamsnap
    networks:
      - streamsnap_network
    labels:
      - "com.centurylinklabs.watchtower.scope=streamsnap"

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: streamsnap-autoheal
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal.streamsnap
      - AUTOHEAL_INTERVAL=5
      - AUTOHEAL_START_PERIOD=30
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
      - AUTOHEAL_ONLY_MONITOR_RUNNING=true
    networks:
      - streamsnap_network
    labels:
      - "com.centurylinklabs.watchtower.scope=streamsnap"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: streamsnap-cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - streamsnap_network
    labels:
      - "com.centurylinklabs.watchtower.scope=streamsnap"
      - "autoheal.streamsnap=true"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://streamsnap:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  streamsnap_network:
    driver: bridge

volumes:
  streamsnap_config:
  streamsnap_logs: