ai_settings:
  azure_openai_endpoint: "https://your-azure-openai-endpoint.openai.azure.com"
  azure_openai_api_key: "your-azure-openai-api-key"
  azure_openai_model: "gpt-4o"
  azure_openai_api_version: "2025-01-01-preview"
  summary_length: 300
  timestamp_threshold: 30.0

processing_settings:
  max_video_duration: 10800  # 3 hours in seconds
  chunk_size: 2000
  prefer_transcript: true
  enable_whisper_transcription: false

slack_settings:
  bot_token: "your-slack-bot-token"
  signing_secret: "your-slack-signing-secret"
  channel_id: "your-channel-id"  # Channel where bot was invited
  auto_process_urls: false
  auto_detect_channels: true  # Automatically process YouTube URLs from any channel bot is invited to

ui_settings:
  app_name: "StreamSnap"
  brand_color: "#116df8"
  accent_color: "#ff5100"